name: share_launcher
description: A launcher that handles share functionality on a device.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.3.0
