name: schedule_exporter_repository
description: Export schedule to device calendar
version: 0.1.0+1
publish_to: none
environment:
  sdk: ">=3.7.0 <4.0.0"
resolution: workspace
dependencies:
  collection: ^1.18.0
  device_calendar:
    git:
      url: https://github.com/0niel/device_calendar.git
      ref: develop
  flutter:
    sdk: flutter
  schedule: any
  timezone: ^0.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: 10.3.0
