name: example
description: OAuth interceptor client example.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.5.1"


dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  web_oauth_interceptor_client:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.3.0

flutter:
  uses-material-design: true
