name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auth_client:
    path: ../auth_client/auth_client
  equatable: ^2.0.3
  deep_link_client:
    path: ../deep_link_client
  package_info_client:
    path: ../package_info_client
  rxdart: ^0.28.0
  storage:
    path: ../storage/storage

dev_dependencies:
  mocktail: ^1.0.2
  test: ^1.21.4
  very_good_analysis: ^6.0.0
