name: university_app
repository: https://github.com/0niel/university-app
sdkPath: .fvm/flutter_sdk
bootstrap:
  runPubGetInParallel: false
packages:
  - packages/*
  - packages/dynamite/**
  - packages/neon/**
  - packages/neon/**/packages/**
  - packages/neon/**/packages/*/neon_framework/packages/**
  - api/**
ide:
  intellij:
    enabled: false
command:
  bootstrap:
    dependency_overrides:
      intl: ^0.18.0
      web: ^1.0.0
    hooks:
      post: melos run format
  version:
    hooks:
      preCommit: |
        melos bootstrap
        git add packages/app/pubspec.lock
scripts:
  format: dart format --fix --line-length 120 .
  format:check: dart format --output=none --set-exit-if-changed --line-length 120 .
  analyze: dart run custom_lint --fatal-infos .
  fix: dart fix --apply
  test: >
    melos exec --no-flutter --concurrency=1 --fail-fast --dir-exists=test -- "dart test --concurrency=$(nproc --all) --fail-fast" &&
    melos exec --flutter --concurrency=1 --fail-fast --dir-exists=test -- "flutter test --concurrency=$(nproc --all)"
  build_runner: dart run build_runner build --delete-conflicting-outputs && melos run format
  generate:neon:build_runner: melos exec --scope="neon*" --file-exists="build.yaml" -- dart run build_runner build --delete-conflicting-outputs && melos run format
  generate:neon:l10n: melos exec --flutter --dir-exists="lib/l10n" flutter gen-l10n && melos run format
