name: "wear"
description: A new Flutter WearOS project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  app_ui:
    path: ../packages/app_ui
  bloc: ^9.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.3.0
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  schedule:
    path: ../packages/schedule
  watch_connectivity: ^0.2.1
  wearable_rotary: ^2.0.2

dependency_overrides:
  enough_platform_widgets:
    git:
      url: https://github.com/Enough-Software/enough_platform_widgets.git
      ref: 38f080f758da42dd9e66d49adbba02aa28d9ff7c
  intl: 0.19.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.0
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  mocktail: ^1.0.4
  very_good_analysis: 10.3.0

flutter:
  uses-material-design: true
  generate: true
