import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as path;

import 'university_deployment_config.dart';

final class UniversityConfigurator {
  UniversityConfigurator({required Directory projectRoot})
    : _projectRoot = projectRoot.absolute;

  final Directory _projectRoot;

  static const _iosExcludedKeys = {
    'UNIVERSITY_WEBSITE_URL',
    'APP_COMMUNITY_CHAT_URL',
    'APP_COMMUNITY_FORUM_URL',
    'APP_CALENDAR_EVENT_URL',
    'APP_NFC_PASS_OAUTH_URL',
    'APP_NFC_PASS_REDIRECT_URLS',
    'APP_NFC_PASS_ACCESS_TOKEN_URL',
    'APP_NFC_PASS_SEND_CODE_URL',
    'APP_NFC_PASS_GET_PASS_URL',
  };

  UniversityDeploymentConfig readConfig(File configFile) {
    if (!configFile.existsSync()) {
      throw UniversityConfigurationException(
        'Configuration file does not exist: ${configFile.path}',
      );
    }
    return UniversityDeploymentConfig.fromJsonString(
      configFile.readAsStringSync(),
    );
  }

  Map<String, String> render(UniversityDeploymentConfig config) => {
    path.join('android', 'tenant.properties'): _renderAndroid(config),
    path.join('ios', 'Flutter', 'Tenant.xcconfig'): _renderIos(config),
    path.join('web', 'university-config.json'): _renderWeb(config),
  };

  UniversityConfigurationCheck check(UniversityDeploymentConfig config) {
    final missing = <String>[];
    final outdated = <String>[];
    for (final entry in render(config).entries) {
      final output = File(path.join(_projectRoot.path, entry.key));
      if (!output.existsSync()) {
        missing.add(entry.key);
      } else if (output.readAsStringSync() != entry.value) {
        outdated.add(entry.key);
      }
    }
    return UniversityConfigurationCheck(
      missingPaths: List.unmodifiable(missing),
      outdatedPaths: List.unmodifiable(outdated),
    );
  }

  UniversityConfigurationWrite write(UniversityDeploymentConfig config) {
    final written = <String>[];
    final unchanged = <String>[];
    for (final entry in render(config).entries) {
      final output = File(path.join(_projectRoot.path, entry.key));
      if (output.existsSync() && output.readAsStringSync() == entry.value) {
        unchanged.add(entry.key);
        continue;
      }
      _writeAtomically(output, entry.value);
      written.add(entry.key);
    }
    return UniversityConfigurationWrite(
      writtenPaths: List.unmodifiable(written),
      unchangedPaths: List.unmodifiable(unchanged),
    );
  }

  String _renderAndroid(UniversityDeploymentConfig config) {
    final values = config.toEnvironmentMap();
    final buffer = StringBuffer(
      '# Generated by tool/configure_university.dart. Do not edit.\n',
    );
    for (final entry in values.entries) {
      buffer
        ..write(_escapeProperties(entry.key))
        ..write('=')
        ..writeln(_escapeProperties(entry.value));
    }
    return buffer.toString();
  }

  String _renderIos(UniversityDeploymentConfig config) {
    final values = config.toEnvironmentMap();
    final buffer = StringBuffer(
      '// Generated by tool/configure_university.dart. Do not edit.\n',
    );
    for (final entry in values.entries) {
      if (_iosExcludedKeys.contains(entry.key)) continue;
      buffer.writeln('TENANT_${entry.key} = ${entry.value}');
    }
    return buffer.toString();
  }

  String _renderWeb(UniversityDeploymentConfig config) {
    final output = <String, Object>{
      'schemaVersion': 1,
      ...config.toEnvironmentMap(),
    };
    return '${const JsonEncoder.withIndent('  ').convert(output)}\n';
  }

  String _escapeProperties(String value) => value
      .replaceAll(r'\', r'\\')
      .replaceAll('=', r'\=')
      .replaceAll(':', r'\:');

  void _writeAtomically(File destination, String contents) {
    destination.parent.createSync(recursive: true);
    final nonce = '${pid}_${DateTime.now().microsecondsSinceEpoch}';
    final temporary = File('${destination.path}.$nonce.tmp');
    final backup = File('${destination.path}.$nonce.bak');
    temporary.writeAsStringSync(contents, flush: true);

    final destinationExisted = destination.existsSync();
    var movedExistingFile = false;
    try {
      if (destinationExisted) {
        destination.renameSync(backup.path);
        movedExistingFile = true;
      }
      temporary.renameSync(destination.path);
      if (movedExistingFile && backup.existsSync()) {
        backup.deleteSync();
      }
    } on Object {
      if (movedExistingFile) {
        if (destination.existsSync()) {
          destination.deleteSync();
        }
        if (backup.existsSync()) {
          backup.renameSync(destination.path);
        }
      } else if (!destinationExisted &&
          destination.existsSync() &&
          !temporary.existsSync()) {
        destination.deleteSync();
      }
      rethrow;
    } finally {
      if (temporary.existsSync()) {
        temporary.deleteSync();
      }
      if (backup.existsSync() && destination.existsSync()) {
        backup.deleteSync();
      }
    }
  }
}

final class UniversityConfigurationCheck {
  const UniversityConfigurationCheck({
    required this.missingPaths,
    required this.outdatedPaths,
  });

  final List<String> missingPaths;
  final List<String> outdatedPaths;

  bool get isCurrent => missingPaths.isEmpty && outdatedPaths.isEmpty;
}

final class UniversityConfigurationWrite {
  const UniversityConfigurationWrite({
    required this.writtenPaths,
    required this.unchangedPaths,
  });

  final List<String> writtenPaths;
  final List<String> unchangedPaths;
}
