name: notifications_client
description: A Generic Notifications Client Interface.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.2 <4.0.0'

dev_dependencies:
  test: ^1.24.6
  very_good_analysis: ^5.1.0
