name: github
description: A client that fetches github data
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  http: ^1.1.2
  equatable: ^2.0.3
  json_annotation: ^4.8.1
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.1.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.21.4
  very_good_analysis: ^5.1.0
