include: ../../analysis_options.yaml

dcm:
  rules:
    # This rule requires Dart 3.10 while this reusable package supports 3.8.
    - prefer-returning-shorthands: false
    - prefer-shorthands-with-enums: false
