name: schedule_api_client
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0