name: schedule_repository
description: A repository that exposes schedule data.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.3
  university_app_server_api:
    path: ../../api

dev_dependencies:
  coverage: ^1.2.0
  mocktail: ^1.0.0
  test: ^1.21.4
  very_good_analysis: ^5.1.0
