name: firebase_notifications_client
description: A Firebase Cloud Messaging notifications client.
version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=3.7.0 <4.0.0'
resolution: workspace
dependencies:
  firebase_messaging: ^16.1.1
  flutter:
    sdk: flutter
  notifications_client: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.24.3
  very_good_analysis: 10.3.0
