name: rtu_mirea_schedule_api_client
description: A package that provides access to the remote schedule API of the RTU MIREA
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  http: ^1.1.2
  icalendar_parser: ^2.0.0
  rrule: ^0.2.14
  equatable: ^2.0.3
  json_annotation: ^4.8.1
  intl: ^0.18.1
  schedule:
    path: ../schedule
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.1.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.21.4
  very_good_analysis: ^5.1.0
