name: permission_client
description: A client that handles requesting permissions on a device.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.3.0
