name: academic_calendar
description: Utility for working with academic calendars.
version: 0.1.1+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
