name: neon_files
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  collection: ^1.0.0
  file_icons:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/file_icons
  file_picker: ^6.0.0
  filesize: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.0.0
  go_router: ^13.0.0
  image_picker: ^1.0.0
  intl: ^0.18.0
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^4.0.0
  open_file: ^3.0.0
  path: ^1.0.0
  path_provider: ^2.0.0
  queue: ^3.0.0
  rxdart: ^0.27.0
  share_plus: ^7.0.0
  universal_io: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.8
  go_router_builder: ^2.4.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/
