name: package_info_client
description: A client that provides information about the app's package metadata
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace
dev_dependencies:
  test: ^1.21.4
  very_good_analysis: 10.3.0
