name: web_oauth_interceptor_client
description: Secure OAuth login interception for Flutter in-app browsers.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.1"

resolution: workspace
dependencies:
  collection: any
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.2.0-beta.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: 10.3.0
