name: nfc_pass_client
description: Configurable gRPC-Web client for university NFC-pass providers.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  grpc: ^5.1.0
  http: ^1.2.2
  protobuf: ^6.0.0
  random_user_agents: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: 10.3.0
