name: notifications_repository
description: A repository that manages notification permissions and topic subscriptions.
version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=3.7.0 <4.0.0'
resolution: workspace
dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  notifications_client: any
  permission_client: any
  storage: any
  test: ^1.24.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: 10.3.0
