include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false

dcm:
  extends:
    - recommended
  exclude:
    all:
      - "**/*.freezed.dart"
      - "**/*.g.dart"
