name: nfc_pass_repository
description: NFC Pass repository package
version: 0.1.0+1
publish_to: none
environment:
  sdk: ^3.5.0
  flutter: ^3.24.0
resolution: workspace
dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.6.0
  nfc_pass_client: any
  storage: any
  web_oauth_interceptor_client: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: 10.3.0
