name: university_app_server_api
description: University app server API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  dart_frog: ^1.0.1
  equatable: ^2.0.5
  http: ^1.1.2
  intl: ^0.18.1
  json_annotation: ^4.6.0

  schedule:
    path: packages/schedule

  github:
    path: packages/github

  rtu_mirea_schedule_api_client:
    path: packages/rtu_mirea_schedule_api_client

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0
