name: permission_client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/permission_client/**"
      - ".github/workflows/permission_client.yaml"
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yml
    with:
      flutter_version: 3.44.2
      working_directory: packages/permission_client
