name: persistent_storage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/storage/persistent_storage/**"
      - ".github/workflows/persistent_storage.yaml"
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yml
    with:
      coverage_excludes: "**/*.g.dart"
      flutter_version: 3.44.2
      working_directory: packages/storage/persistent_storage
