name: schedule_api_client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".fvmrc"
      - "pubspec.yaml"
      - "pubspec.lock"
      - ".github/workflows/flutter_package.yml"
      - "packages/rtu_mirea_schedule_api_client/**"
      - ".github/workflows/schedule_api_client.yaml"
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yml
    with:
      coverage_excludes: "**/*.g.dart"
      min_coverage: 75
      working_directory: packages/rtu_mirea_schedule_api_client
