// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'post.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Post _$PostFromJson(Map<String, dynamic> json) => _Post(
  id: (json['id'] as num).toInt(),
  username: json['username'] as String,
  avatarTemplate: json['avatar_template'] as String,
  createdAt: json['created_at'] as String,
  cooked: json['cooked'] as String,
  postNumber: (json['post_number'] as num).toInt(),
  postType: (json['post_type'] as num).toInt(),
  updatedAt: json['updated_at'] as String,
  replyCount: (json['reply_count'] as num).toInt(),
  replyToPostNumber: json['reply_to_post_number'],
  quoteCount: (json['quote_count'] as num).toInt(),
  incomingLinkCount: (json['incoming_link_count'] as num).toInt(),
  reads: (json['reads'] as num).toInt(),
  readersCount: (json['readers_count'] as num).toInt(),
  score: (json['score'] as num).toDouble(),
  yours: json['yours'] as bool,
  topicId: (json['topic_id'] as num).toInt(),
  topicSlug: json['topic_slug'] as String,
  displayUsername: json['display_username'] as String,
  version: (json['version'] as num).toInt(),
  canEdit: json['can_edit'] as bool,
  canDelete: json['can_delete'] as bool,
  canRecover: json['can_recover'] as bool,
  canSeeHiddenPost: json['can_see_hidden_post'] as bool,
  canWiki: json['can_wiki'] as bool,
  bookmarked: json['bookmarked'] as bool,
  raw: json['raw'] as String,
  actionsSummary: json['actions_summary'] as List<dynamic>,
  moderator: json['moderator'] as bool,
  admin: json['admin'] as bool,
  staff: json['staff'] as bool,
  userId: (json['user_id'] as num).toInt(),
  hidden: json['hidden'] as bool,
  trustLevel: (json['trust_level'] as num).toInt(),
  deletedAt: json['deleted_at'],
  userDeleted: json['user_deleted'] as bool,
  canViewEditHistory: json['can_view_edit_history'] as bool,
  wiki: json['wiki'] as bool,
  mentionedUsers: json['mentioned_users'] as List<dynamic>,
  calendarDetails: json['calendar_details'] as List<dynamic>,
  canManageCategoryExpertPosts:
      json['can_manage_category_expert_posts'] as bool,
  ratings: json['ratings'] as List<dynamic>,
  reactions: json['reactions'] as List<dynamic>,
  reactionUsersCount: (json['reaction_users_count'] as num).toInt(),
  currentUserUsedMainReaction: json['current_user_used_main_reaction'] as bool,
  canAcceptAnswer: json['can_accept_answer'] as bool,
  canUnacceptAnswer: json['can_unaccept_answer'] as bool,
  acceptedAnswer: json['accepted_answer'] as bool,
  topicAcceptedAnswer: json['topic_accepted_answer'] as bool,
  name: json['name'] as String?,
  primaryGroupName: json['primary_group_name'] as String?,
  flairName: json['flair_name'] as String?,
  flairUrl: json['flair_url'] as String?,
  flairBgColor: json['flair_bg_color'] as String?,
  flairColor: json['flair_color'] as String?,
  flairGroupId: (json['flair_group_id'] as num?)?.toInt(),
  userTitle: json['user_title'] as String?,
  editReason: json['edit_reason'],
  reviewableId: json['reviewable_id'],
  reviewableScoreCount: (json['reviewable_score_count'] as num?)?.toInt(),
  reviewableScorePendingCount: (json['reviewable_score_pending_count'] as num?)
      ?.toInt(),
  event: json['event'],
  categoryExpertApprovedGroup: json['category_expert_approved_group'],
  needsCategoryExpertApproval: json['needs_category_expert_approval'],
  userNftVerified: json['user_nft_verified'],
  currentUserReaction: json['current_user_reaction'],
);

Map<String, dynamic> _$PostToJson(_Post instance) => <String, dynamic>{
  'id': instance.id,
  'username': instance.username,
  'avatar_template': instance.avatarTemplate,
  'created_at': instance.createdAt,
  'cooked': instance.cooked,
  'post_number': instance.postNumber,
  'post_type': instance.postType,
  'updated_at': instance.updatedAt,
  'reply_count': instance.replyCount,
  'reply_to_post_number': instance.replyToPostNumber,
  'quote_count': instance.quoteCount,
  'incoming_link_count': instance.incomingLinkCount,
  'reads': instance.reads,
  'readers_count': instance.readersCount,
  'score': instance.score,
  'yours': instance.yours,
  'topic_id': instance.topicId,
  'topic_slug': instance.topicSlug,
  'display_username': instance.displayUsername,
  'version': instance.version,
  'can_edit': instance.canEdit,
  'can_delete': instance.canDelete,
  'can_recover': instance.canRecover,
  'can_see_hidden_post': instance.canSeeHiddenPost,
  'can_wiki': instance.canWiki,
  'bookmarked': instance.bookmarked,
  'raw': instance.raw,
  'actions_summary': instance.actionsSummary,
  'moderator': instance.moderator,
  'admin': instance.admin,
  'staff': instance.staff,
  'user_id': instance.userId,
  'hidden': instance.hidden,
  'trust_level': instance.trustLevel,
  'deleted_at': instance.deletedAt,
  'user_deleted': instance.userDeleted,
  'can_view_edit_history': instance.canViewEditHistory,
  'wiki': instance.wiki,
  'mentioned_users': instance.mentionedUsers,
  'calendar_details': instance.calendarDetails,
  'can_manage_category_expert_posts': instance.canManageCategoryExpertPosts,
  'ratings': instance.ratings,
  'reactions': instance.reactions,
  'reaction_users_count': instance.reactionUsersCount,
  'current_user_used_main_reaction': instance.currentUserUsedMainReaction,
  'can_accept_answer': instance.canAcceptAnswer,
  'can_unaccept_answer': instance.canUnacceptAnswer,
  'accepted_answer': instance.acceptedAnswer,
  'topic_accepted_answer': instance.topicAcceptedAnswer,
  'name': instance.name,
  'primary_group_name': instance.primaryGroupName,
  'flair_name': instance.flairName,
  'flair_url': instance.flairUrl,
  'flair_bg_color': instance.flairBgColor,
  'flair_color': instance.flairColor,
  'flair_group_id': instance.flairGroupId,
  'user_title': instance.userTitle,
  'edit_reason': instance.editReason,
  'reviewable_id': instance.reviewableId,
  'reviewable_score_count': instance.reviewableScoreCount,
  'reviewable_score_pending_count': instance.reviewableScorePendingCount,
  'event': instance.event,
  'category_expert_approved_group': instance.categoryExpertApprovedGroup,
  'needs_category_expert_approval': instance.needsCategoryExpertApproval,
  'user_nft_verified': instance.userNftVerified,
  'current_user_reaction': instance.currentUserReaction,
};
